---
- hosts: webservers
  user: sysadmin
  become: yes
  gather_facts: no

  tasks:

    - name: Aplico medidas de seguridad a SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.abuscar }}"
        line: "{{ item.reemplazo }}"
      loop:
        - { abuscar: '#PermitRootLogin', reemplazo: 'PermitRootLogin no' }
        - { abuscar: '#AuthenticationMethedos', reemplazo: 'AuthenticationMethods publickey' } 
        - { abuscar: '#PubkeyAuthentication', reemplazo: 'PubkeyAuthentication yes' }
      notify: Reinicio SSH
 
  handlers:
    - name: Reinicio SSH
      service:
        name: "{{ ssh_service }}"
        state: restarted

...
