---
- hosts: webservers
  user: sysadmin
  become: yes

  tasks:

  - name: Asegurar paquete apache instalado
    ansible.builtin.package:
      name: "{{ apache_service }}"
      state: latest
    notify: Reiniciar webserver
      
  - name: Asegurar archivo index.html esta presente
    copy:
      src: ./files/index.html
      dest: /var/www/html/index.html

  - name: Habilitar puerto HTTPD/80 en FirewallD 
    ansible.posix.firewalld:
      service: http
      state: enabled
      permanent: true
      immediate: true
      offline: true
    when: ansible_facts['os_family'] == "RedHat"
  
  - name: Habilitar puerto SSH/22 en ufw
    community.general.ufw:
      rule: allow
      state: enabled
      port: ssh
      proto: tcp
    when: ansible_facts['os_family'] == "Debian"

  - name: Habilitar puerto HTTPD/80 en ufw
    community.general.ufw:
      rule: allow
      state: enabled
      port: http
      proto: tcp
    when: ansible_facts['os_family'] == "Debian"

  handlers:

    - name: Reiniciar webserver
      service:
        name: "{{ apache_service }}"
        state: restarted
...
