   - name: Habilitar puerto {{ item }} en ufw
     community.general.ufw:
       rule: allow
       state: enabled
       port: "{{ item }}"
       proto: tcp
     when: ansible_facts['os_family'] == "Debian"
      
